### ISSUE TITLE
issue with output

### ISSUE THREAD

**Issue by justinhamlin** [learn-co-curriculum/scraping-flatiron-code-along#17]
Hello, I was trying to follow along with this lesson but was having issues producing the same Nokogiri output on my end. Gabe Jackson helped me figure out that I needed to chain a ".inspect" method on the end of the code in my editor in order for it to work. So for example the below code should have ".inspect" at the end for me to have the same output that the lesson is saying I should be seeing.

require 'nokogiri'
require 'open-uri'

doc = Nokogiri::HTML(open("http://flatironschool.com/"))

doc.css(".grey-text")

puts doc.css(".grey-text")

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
