### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/scraping-flatiron-code-along#23]
https://learn.co/tracks/full-stack-web-development/object-oriented-ruby/scraping/scraping-lab#fullscreen

Currently reads:
Go back to the site and open up the element inspector again. Use the magnifying class symbol...

Should read:
Go back to the site and open up the element inspector again. Use the magnifying c=glass symbol...

Thanks,
Scott
![image](https://cloud.githubusercontent.com/assets/17987990/22709912/560ffc9c-ed30-11e6-9ef5-33c7628da76e.png)

**Comment by aturkewi** [comment]
Fixed with PR #24 
Also, feel free to make the PR by using the PR button in Learn rather than the Raise Issue button (they're right next to each other).

Thanks for pointing this out :)
