### ISSUE TITLE
Tests need to be made more robust

### ISSUE THREAD

**Issue by aaronkelton** [learn-co-curriculum/scraping-flatiron-code-along#25]
Tests for `#get_courses` and `#make_courses` are passing when they shouldn't. See attached screenshot.

![scraping-flatiron-code-along-passes-test-but-shouldnt](https://cloud.githubusercontent.com/assets/6170077/25869099/c5428478-34c4-11e7-9bf3-486b1dcaaec3.png)

**Comment by curiositypaths** [comment]
Hi there,

Following your suggestion, we improved the Scraper test coverage.

As always, thanks for contributing! 💙
