### ISSUE TITLE
"cannot load such file -- nokogiri (Load Error)" on Learn IDE 3.7.0 and Windows 10 64-bit

### ISSUE THREAD

**Issue by BeejLuig** [learn-co-curriculum/scraping-flatiron-code-along#27]
A student couldn't proceed with the lab because she was running into the above error. Uninstalling and re-installing nokogiri (various versions between 1.6-1.8) proved unsuccessful. I made sure that we removed the lab and re-cloned it to start fresh, but the issue persisted.

 Creating this issue in case another Windows user with the new IDE has the same problem. See screenshot below for details. 

![aa3f9b77-04b6-4e54-966d-42613c047574](https://user-images.githubusercontent.com/15836789/29906425-d9fde30e-8de2-11e7-8cac-573adb456189.png)

**Comment by curiositypaths** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

I'm sorry, and good luck! 💙
