### ISSUE TITLE
Spelling error in text

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/scraping-flatiron-code-along#28]
For each iteration over the collection of Nokogiri XML elements returned to **use** [should be "us"] by the doc.css(".post") line, we are making a new instance of the Course class and giving that instance the title, schedule and description extracted from the XML.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the correction. We updated the lesson README.

As always, thanks for contributing! 💙
