### ISSUE TITLE
potentially confusing typo in the class methods .all rspec of the Course class for "an"

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/scraping-flatiron-code-along#29]
Course
  instance methods
    #title
      has a setter and a getter method for title
    #schedule
      has a setter and a getter method for a course's schedule
    #description
      has a setter and a getter method for a course's description
  class methods
    .all
      returns **and** array of all the instances of the Course class (FAILED - 1)

**Comment by drakeltheryuujin** [comment]
Hi @ode-to-the-code,

Thank you for your feedback. It has been updated on our repo. If you feel that the issue has not been fixed, feel free to re-open the issue and give details as to what can be done to resolve it.

Thanks again 💙
