### ISSUE TITLE
#print_courses method is missing

### ISSUE THREAD

**Issue by jamcelr** [learn-co-curriculum/scraping-flatiron-code-along#8]
The curriculum mentions that a #print_courses method was provided as a 'freebie' for this lab in the scraper.rb file.  However, this is no #print_courses method already predefined in the scraper.rb file.  Near the end of the lab, the curriculum asks students to run **Scraper.new.print_courses** but again, there is no method defined for #print_courses until you scroll to the bottom of the curriculum, where a screenshot shows the #print_courses method as:

  def print_courses
    self.make_courses
    Course.all.each do |course|
      if course.title
        puts "Title: #{course.title}"
        puts "  Schedule: #{course.schedule}"
        puts "  Description: #{course.description}"
      end
    end
  end

**Comment by AnnJohn** [comment]
thanks for raising this issue @jamcelr. We'll look into it as soon as we can.

**Comment by AnnJohn** [comment]
updated with the method. thanks!
